=== achrafbchir/ensat_xml_project/public/notes.dtd
<!ELEMENT notes (note*)>
<!ELEMENT note (FirstName, LastName, ClassName, ModuleName, ElementName, NoteElement)>
<!ELEMENT FirstName (#PCDATA)>
<!ELEMENT LastName (#PCDATA)>
<!ELEMENT ClassName (#PCDATA)>
<!ELEMENT ModuleName (#PCDATA)>
<!ELEMENT ElementName (#PCDATA)>
<!ELEMENT NoteElement (#PCDATA)>

=== achrafbchir/ensat_xml_project/public/Ginf3_Notes.xml
<?xml version="1.0"?>
<!DOCTYPE notes SYSTEM "notes.dtd">
<notes><note><FirstName>Achraf</FirstName><LastName>Bchir</LastName><ClassName>GINF3</ClassName><ModuleName>Java/xml</ModuleName><ElementName>java</ElementName><NoteElement>17</NoteElement></note><note><FirstName>Nizar</FirstName><LastName>Laadnani</LastName><ClassName>GINF4</ClassName><ModuleName>Java/xml</ModuleName><ElementName>java</ElementName><NoteElement>15</NoteElement></note><note><FirstName>Amine</FirstName><LastName>Afendi</LastName><ClassName>GINF5</ClassName><ModuleName>Java/xml</ModuleName><ElementName>java</ElementName><NoteElement>18</NoteElement></note><note><FirstName>Naji</FirstName><LastName>Naji</LastName><ClassName>GINF6</ClassName><ModuleName>Java/xml</ModuleName><ElementName>java</ElementName><NoteElement>14</NoteElement></note><note><FirstName>Saad</FirstName><LastName>Ramane</LastName><ClassName>GINF7</ClassName><ModuleName>Java/xml</ModuleName><ElementName>java</ElementName><NoteElement>14</NoteElement></note></notes>
